---

root: true

plugins:
  - jest

env:
  node: true
  jest: true
  es2020: true

parserOptions:
  ecmaVersion: 2020

extends:
  - 'airbnb-base'
  - 'plugin:jest/recommended'

rules:
  no-console: 0
  import/extensions: 0
  import/prefer-default-export: 0
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }]
